apiVersion: v1
kind: Service
metadata:
  name: new-existingdockerfilegeneratedeployment
  namespace: namespace-workflow-1729284309209
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: new-existingdockerfilegeneratedeployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80