apiVersion: v1
kind: Service
metadata:
  name: workflow2
  namespace: sample-app-namespace-1730324645947
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: workflow2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80